#!/bin/bash -x
echo
echo DEBUG: build start
echo
pwd
ls -la
ls -la /root
docker buildx create --name myBuilder --use --bootstrap
docker buildx ls
docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64  -t naoso5/test-sshd --push .
